interface eth0
    ip pim
    ip igmp

interface eth1
    ip pim
    ip igmp

interface eth2
    ip pim
    ip igmp

router ospf
    redistribute connected
    network 0.0.0.0/0 area 0

router pim
    autorp discovery
    autorp announce 10.0.4.2 224.0.0.0/4
    autorp announce interval 5
