interface eth0
    ip pim
    ip igmp

interface eth1
    ip pim
    ip igmp

interface eth2
    ip pim
    ip igmp

router ospf
    redistribute connected
    network 0.0.0.0/0 area 0

router pim
    bsr candidate-bsr source address 10.0.4.3
