
up:
	sudo python3 topology.py

down:
	sudo mn -c

static:
	sudo python3 topology.py --static

.PHONY: rip
rip:
	sudo python3 topology.py --rip

ospf:
	sudo python3 topology.py --ospf

eigrp:
	sudo python3 topology.py --eigrp

clean:
	sudo mn -c
